### ISSUE TITLE
Rotate Webcam Output: 10 degrees

### ISSUE THREAD

**Issue by victorevector** [Robo3D/OctoPrint-robotheme#10]
# issue

Webcam output is tilted because of the camera's embedded position. 

# Proposed Solution & Reasoning

Using JS, rotate and crop the video stream until it looks straight. 10 degrees looks best. 

We'll have to perform the fix here because mjpg_streamer does not support the rotation value we need: 0, 90, 270, 360.

**Comment by OutsourcedGuru** [comment]
For what it's worth, main.css in OctoPrint-robotheme includes two locations for #webcam_image rather than just once. The second instance, as edited, appears in the Media Query section at the end for "E. Between 980px and 1199px". The first one wasn't apparently edited.
