### ISSUE TITLE
[BUG] Custom Temperature (Preset) field problematic

### ISSUE THREAD

**Issue by OutsourcedGuru** [Robo3D/Octoprint-robotheme#32]
### What did you do?
OctoPrint -> Settings -> Temperatures -> create custom filament "SHAXON CARBON FIBER INFUSED"

### What did you expect to happen?
I expected the UX to reasonably display a button in the temperature presets.

### What happened instead?
The input field suggests that it can accept arbitrarily-long field names although realistically, it should be exactly three characters in order to render correctly.  Additionally, the spaces were removed for the button's text.

![screen shot 2018-01-11 at 1 31 24 pm](https://user-images.githubusercontent.com/15971213/34848616-42d5dee0-f6d4-11e7-80bc-738a0a30772a.png)

![screen shot 2018-01-11 at 1 29 13 pm](https://user-images.githubusercontent.com/15971213/34848639-4eacf8c0-f6d4-11e7-8fd3-5e3e9d33e247.png)

### What version of RoboOS are you using?
1.8.0-r2.0

### Link copy of octoprint.log or paste raw lines:

[gist.github.com or pastebin.com are resources to save and share documents]

### Screenshot(s) or video(s) showing the problem:

[optional but very helpful]

**Comment by AllenMcAfee** [comment]
@OutsourcedGuru check out the dev branch to see where we're going with this.  We're dropping the custom field in favor of Octoprint's default layout.  It will be easier to maintain compatibility with their future changes this way.  We just want to restyle the CSS here.
