### ISSUE TITLE
More of a query regarding dev-bugfix branch

### ISSUE THREAD

**Issue by OutsourcedGuru** [Robo3D/Octoprint-robotheme#39]
@AllenMcAfee Was wondering if there was a purpose to "aelse" on the .ajax call in /static/js/robotheme.js in fetching/displaying the printer's name. It looks like an intentional typo to prevent the else but I have to ask.

**Comment by AllenMcAfee** [comment]
@OutsourcedGuru Are you talking about the .ajax call starting on line 360?  I'm not seeing an "aelse" in there.

**Comment by OutsourcedGuru** [comment]
Looks like [aelse made it in there](https://github.com/Robo3D/OctoPrint-robotheme/commit/192ea7393293d987049bd2422dc8c79d75ff4ff8) and [then came out](https://github.com/Robo3D/OctoPrint-robotheme/commit/3916de0cdef2f0c6918dee7d2e45aebe135eff93). I was wondering if you were purposely preventing the else from working. This is the `success()` under the ajax.
