### ISSUE TITLE
UI is not compatible with 1.3.1

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/OctoPrint-robotheme#9]
The Robotheme UI is breaking with the release of Octoprint 1.3.1 Investigation is under way.

@victorevector You had said there was some sort of JS error?

**Comment by victorevector** [comment]
# Update 3/16/2017

Looks like the UI is also breaking on machines installed with[ 1.3.0-RoboOS](https://github.com/Robo3D/OctoPrint/releases/tag/1.3.0-roboOS).
